local builtin = require("trouble")
vim.keymap.set("n", "<leader>xx", function() builtin.toggle() end)
vim.keymap.set("n", "<leader>xw", function() builtin.toggle("workspace_diagnostics") end)
vim.keymap.set("n", "<leader>xd", function() builtin.toggle("document_diagnostics") end)
vim.keymap.set("n", "<leader>xq", function() builtin.toggle("quickfix") end)
vim.keymap.set("n", "<leader>xl", function() builtin.toggle("loclist") end)
vim.keymap.set("n", "gR", function() builtin.toggle("lsp_references") end)
